### ISSUE TITLE
API 문서 요청

### ISSUE THREAD

**Issue by jeehoonkang** [kim-sanghoon/chatbot#2]
혹시 http endpoint의 api를 문서화해주실 수 있으실지 여쭤보고 싶습니다.

**Comment by kim-sanghoon** [comment]
현재 코드에 구현되어 있는 API들은 Google Dialogflow의 [Webhook request](https://cloud.google.com/dialogflow/es/docs/fulfillment-webhook)를 처리하기 위한 목적입니다.
데모 구현 및 다른 애플리케이션 연동에 필요한 API는 따로 구현되어 있지 않아서, 향후에 그런 기능이 추가되면 Wiki 등으로 문서화하도록 하겠습니다.

**Comment by jeehoonkang** [comment]
말씀하신 사안을 readme에 document해주실 수 있을까요?
아울러 구체적으로 어디에 endpoint가 생기는지 적어주시면 좋을 것 같습니다.

**Comment by kim-sanghoon** [comment]
작성해두었습니다: https://github.com/kim-sanghoon/chatbot/commit/dd03382727a73ebc3dff31057c6b91b86fa5696c

**Comment by jeehoonkang** [comment]
감사합니다!
