### ISSUE TITLE
master vs. becs-demo branch

### ISSUE THREAD

**Issue by jeehoonkang** [kim-sanghoon/chatbot#3]
master로 머지를 꺼리시는 이유가 궁금합니다. 가령 requirements.txt를 추가한건 (단순히 데모 목적이 아니라) 개발 목적으로 충분한 이유가 되는 것 같아서요.

**Comment by kim-sanghoon** [comment]
PR주신 내용 중에서 https -> http 로 수정한 부분을 반영하기 위해 becs-demo 브랜치를 따로 만들었습니다.
제가 자연어 처리를 위해 사용하는 Google Dialogflow에서 Webhook을 사용할 경우 https를 강제하고 있어서, Dialogflow에서 직접 Webhook 호출이 불가능합니다.

**Comment by jeehoonkang** [comment]
#4 에서 논의를 이어가겠습니다.
